services:
  selenium:
    container_name: "${COMPOSE_PROJECT_NAME}-selenium"
    image: "selenium/standalone-${MDC_BEHAT_BROWSER}:${MDC_BEHAT_BROWSER_VERSION}"
    shm_size: 2gb
    volumes:
      - "${MDC_DIRROOT}:/var/www/html:ro"
#      - /dev/shm:/dev/shm
    environment:
      # Allow new behat after CTRL-C, the aborted sessions will time out in 300 seconds by default.
      SE_NODE_MAX_SESSIONS: 8
      SE_NODE_OVERRIDE_MAX_SESSIONS: true
